@host = localhost:8080


GET http://{{host}}/status HTTP/1.1 Authorization: Bearer {{access_token}} content-type: application/json

###

GET http://{{host}}/tabledata HTTP/1.1 Authorization: Bearer {{access_token}} content-type: application/json

###


POST http://{{host}}/signin HTTP/1.1 Authorization: Bearer {{access_token}} 
content-type: application/json

{
    "user": "user1",
    "password": "Password2"
}

###


POST http://{{host}}/signin HTTP/1.1 Authorization: Bearer {{access_token}} 
content-type: application/json

{
    "user": "martin",
    "password": "Password1"
}

###
# get, post, put, delete, patch